import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  weight: "600",
  variable: "--font-rubik",
  subsets: ["latin"],
});

const inter = Inter({
  weight: "600",
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
